### ISSUE TITLE
no module named 'mido' whilst mido is already satisfied

### ISSUE THREAD

**Issue by GXboy12345** [AlexApps99/MIDI2Desmos#1]
when I use 
`pip install mido`
I get
`Requirement already satisfied: mido in c:\users\***\appdata\local\programs\python\python311\lib\site-packages (1.2.10)`
But when running 
`python3 graph.py Pianoman.mid 1 100 0`
I get 
`Traceback (most recent call last):
  File "***********************\MIDI2Desmos\graph.py", line 19, in <module>
    from mido import MidiFile
ModuleNotFoundError: No module named 'mido'`
Any help?

**Comment by AlexApps99** [comment]
That seems like a misconfigured Python environment, I can't really help with that sorry.
